#!/bin/bash -f

PKG=/fusion/usc/opt/intel2019
# export MKL_LIBDIR=${PKG}/compilers_and_libraries/linux/mkl/lib/intel64
export MKL_LIBDIR=/opt/intel/oneapi/mkl/latest/lib/intel64
export NAGLIB=joe_OPEN_ASTRA_RC_please
export COMP_LIB=${PKG}/compilers_and_libraries/linux/lib/intel64
echo COMP_LIB ${COMP_LIB}
# export I_MPI_ROOT=/fusion/usc/opt/mpich/mpich-3.2/intel2018
export I_MPI_ROOT=/opt/intel/oneapi/mpi/latest
export IFORT_BIN=${PKG}/compilers_and_libraries/linux/bin/intel64
# export MPIFORT_BIN=/fusion/usc/opt/mpich/mpich-3.2/intel2018/bin
export MPIFORT_BIN=${I_MPI_ROOT}/bin
export INTEL_LICENSE_FILE=${PKG}/licenses

export AFC=ifort
export ACC="gcc -O"
# export MPIFC=mpifort
export MPIFC="${MPIFORT_BIN}/mpifc -fc=ifort"

export ASTRA_EXT=pre_comp_lib
#/fusion/projects/codes/astra/ASTRA_LIBRARIES_EXT

# MPI
export MPI_INC="-I${I_MPI_ROOT}/include"
export MPI_LIB="-L${I_MPI_ROOT}/lib -lmpi"

# NetCDF

# Joe: found these vaues from /fusion/projects/theory/gacode/platform/build/make.inc.IRIS
# export NCDF_HOME=/fusion/projects/theory/HPC
export NCDF_HOME=netcdf
# export NCDF_LIB="-L${NCDF_HOME}/fortran/lib -lnetcdff -L${NCDF_HOME}/netcdf/lib -lnetcdf -lnetcdf -L${COMP_LIB} -ldl -lm -lifport -lintlc -lifcoremt -limf -lsvml -lifcore"
# export NCDF_INC=${NCDF_HOME}/fortran/include
export NCDF_INC=${NCDF_HOME}/include

# TORBEAM

IRC_LIB="-L${COMP_LIB} -lirc" # necessary for libtorbeam.so
export TORB_HOME="${ASTRA_EXT}/torbeam/aug21_ifort"
TORB_LIBDIR=${TORB_HOME}/lib
export TORB_LIB="-L${TORB_LIBDIR} -ltorbeamB  -Wl,-rpath,${TORB_LIBDIR} ${IRC_LIB}"

# RABBIT

# export RABBIT_LIBDIR="/fusion/projects/toolbox/energetic_particles/weilandm/rabbit/v4.0.1"
export RABBIT_LIBDIR=pre_comp_lib/rabbit/jul22/lib
# export RABBIT_LIB="-L${RABBIT_LIBDIR} -lrabbit -Wl,-rpath,${RABBIT_LIBDIR}"
export RABBIT_LIB="-L${RABBIT_LIBDIR} -lRabbitMore -Wl,-rpath,${RABBIT_LIBDIR}"
# export RABBIT_INC="/fusion/projects/toolbox/energetic_particles/weilandm/rabbit/v4.0.1/modules"
export RABBIT_INC=pre_comp_lib/rabbit/jul22/inc

# QuaLiKiZ

export QLK_HOME=${ASTRA_EXT}/qualikiz/apr21
export QLK_INC=${QLK_HOME}/inc
# export QLK_LIB=${QLK_HOME}/lib/libqualikiz.a
export QLK_LIB=${QLK_HOME}/lib/libQLK-intel-release-default-mpi.a

export QLKNN_HOME=${ASTRA_EXT}/qlk_nn/apr21
export QLKNN_INC=${QLKNN_HOME}/inc/serial
export QLKNN_LIB=${QLKNN_HOME}/lib/libQLKNN-intel-release-default.a

# TGLF

export TGLF_HOME=${ASTRA_EXT}/tglf/oct22
export TGLF_INC=${TGLF_HOME}/inc
export TGLF_LIB=${TGLF_HOME}/lib/libtglf.a

# NEO

export NEO_HOME=${ASTRA_EXT}/neo/apr21
export NEO_INC=${NEO_HOME}/inc
export NEO_LIB="${NEO_HOME}/lib/neo_lib.a ${NEO_HOME}/lib/nclass_lib.a ${NEO_HOME}/lib/UMFPACK_lib.a ${NEO_HOME}/lib/math_lib.a ${NEO_HOME}/lib/expro_lib.a ${NEO_HOME}/lib/geo_lib.a"

# NAGs

#export NAGFLIB=${NAGLIB}/libnag_nag.a
#export NAGF90MKL=${NAGLIB}/libnag_mkl.a

# XLBR

# export XLBR="-L/usr/lib64 -lX11 -Wl,--start-group ${COMP_LIB}/libintlc.so.5 ${MKL_LIBDIR}/libmkl_intel_lp64.a ${MKL_LIBDIR}/libmkl_core.a ${MKL_LIBDIR}/libmkl_sequential.a ${MKL_LIBDIR}/libmkl_blacs_intelmpi_lp64.a -Wl,--end-group"
export XLBR="-L/usr/lib64 -lX11"

# export AS_LD_LIBRARY_PATH="${NCDF_HOME}/netcdf/lib:${NCDF_HOME}/fortran/lib:${COMP_LIB}:${NAGLIB}"
