#!/bin/bash -f

rootdir=`dirname $0`          # may be relative path
AWD=`cd $rootdir && pwd`  # ensure absolute path
node=`uname -n`

if [[ $AWD == "/afs/eufus"* ]]
then
   platform=gway
elif [[ $AWD == "/localhome"* ]]
then
   platform=goblin
elif [[ $AWD == "/home/ITER"* ]]
then
   platform=iter
elif [[ $AWD == "/compass"* ]]
then
   platform=cz
elif [[ $node == *"mit.edu" ]]
then
   platform=mit
elif [[ $node == "omega"* ]]
then
   platform=omega
elif [[ $node == "CX-LD-AUG"* ]]
then
   platform=ldaug
elif [[ $node == "CX-LD-DSK"* ]]
then
   platform=lddsk
elif [[ $node == "tok"* ]]
then
   platform=tok
elif [[ $node == "iris"* ]]
then
   platform=iris
fi

echo $platform
