subroutine a2json
! Please do not edit this file, nor take a copy from a different commit of the git repo

use parameters_a2equil, only: equil_now
use parameter_inc
use const_inc
use status_inc
use outcmn_inc, only: AWD, exp_file, equ_file

implicit none

logical, parameter :: verbose=.True.
integer, parameter :: l_name=8, l_unit=25, l_desc=60, nunit=25

integer :: jid, jrho, nvars, ios, j_call=1, nrho_surf, nthe_surf, ndim
character(len=120) :: file_in, feq_2d, json_out
character(len=l_name), allocatable, dimension(:) :: s_name
character(len=l_unit), allocatable, dimension(:) :: s_unit
character(len=l_desc), allocatable, dimension(:) :: s_desc
double precision, dimension(200) :: time_traces
integer, external :: get_nvars

save j_call

nrho_surf = SIZE(equil_now%profiles_1d%rho_tor)
nthe_surf = SIZE(equil_now%coord_sys%position%teta2d)

if (verbose) write(*, '(A, i)') 'Starting a2json', j_call
feq_2d = TRIM(AWD) // '/main/equil_2d.txt'

write(json_out, '(5A, i0, A)') TRIM(awd), '/ncdf_out/', TRIM(exp_file), TRIM(equ_file), '-', j_call, '.json'

open(nunit, file=TRIM(json_out), iostat=ios)
write(nunit, '(A\)') '{'

!-----------
! Scalars
!-----------
file_in = TRIM(AWD) // '/main/variables.txt'
call write_scalar_block(nunit, file_in, DEVAR)
file_in = TRIM(AWD) // '/main/variables_x.txt'
call write_scalar_block(nunit, file_in, DEVARX)
file_in = TRIM(AWD) // '/main/constants.txt'
call write_scalar_block(nunit, file_in, CONSTF)
file_in = TRIM(AWD) // '/main/internal.txt'
call write_scalar_block(nunit, file_in, DELOUT)

! Sparse scalars

file_in = TRIM(AWD) // '/main/intern2.txt'
time_traces(1) = TSTART
time_traces(2) = TAU
time_traces(3) = TAUPRP
time_traces(4) = HRO
time_traces(5) = HROX
time_traces(6) = ALBPL
time_traces(7) = NNCX
time_traces(8) = QETB
time_traces(9) = QFF0B
time_traces(10) = QFF1B
time_traces(11) = QFF2B
time_traces(12) = QFF3B
time_traces(13) = QFF4B
time_traces(14) = QFF5B
time_traces(15) = QFF6B
time_traces(16) = QFF7B
time_traces(17) = QFF8B
time_traces(18) = QFF9B
time_traces(19) = QITB
time_traces(20) = QNNB
time_traces(21) = FTO
time_traces(22) = FTN
time_traces(23) = BTN
time_traces(24) = IPLN
time_traces(25) = IFBEY
time_traces(26) = ROB
time_traces(27) = ROWALL
time_traces(28) = ROC
time_traces(29) = ROCO
time_traces(30) = RON
time_traces(31) = ROE
time_traces(32) = ROI
time_traces(33) = RO0
time_traces(34) = RO1
time_traces(35) = RO2
time_traces(36) = RO3
time_traces(37) = RO4
time_traces(38) = RO5
time_traces(39) = RO6
time_traces(40) = RO7
time_traces(41) = RO8
time_traces(42) = RO9
time_traces(43) = ROU
time_traces(44) = VOLUME
time_traces(45) = PSIAX
time_traces(46) = PSIBO
time_traces(47) = GP
time_traces(48) = GP2
time_traces(49) = PSIFB
time_traces(50) = PSIFBO
time_traces(51) = PSIEXT
time_traces(52) = PSPLEX
time_traces(53) = PSIEXO
time_traces(54) = PSPLXO
time_traces(55) = IPLFBE
time_traces(56) = ATREQ
time_traces(57) = PTREQ
time_traces(58) = RBDOT
time_traces(59) = BBDOT
time_traces(60) = NA
time_traces(61) = NA1
time_traces(62) = NA1N
time_traces(63) = NA1E
time_traces(64) = NA1I
time_traces(65) = NA1U
time_traces(66) = NA10
time_traces(67) = NA11
time_traces(68) = NA12
time_traces(69) = NA13
time_traces(70) = NA14
time_traces(71) = NA15
time_traces(72) = NA16
time_traces(73) = NA17
time_traces(74) = NA18
time_traces(75) = NA19
time_traces(76) = NAB
time_traces(77) = ITREQ
time_traces(78) = NITOT
time_traces(79) = NSTEPS
time_traces(80) = QBEAM
call write_scalar_block(nunit, file_in, time_traces)

!-----------
! Profiles
!-----------

! Exp profiles

file_in = TRIM(AWD) // '/main/profiles_x.txt'
if (allocated(s_name)) then
    deallocate(s_name)
    deallocate(s_unit)
    deallocate(s_desc)
endif
nvars = get_nvars(file_in)
allocate(s_name(nvars), s_unit(nvars), s_desc(nvars))
call getAttributes(file_in, nvars, s_name, s_desc, s_unit)
do jid=1, nvars
    call write_array(nunit, NA1, EXT(1:NA1, jid), s_name(jid), s_unit(jid), s_desc(jid))
enddo

! CAR profiles

file_in = TRIM(AWD) // '/main/profiles.txt'
deallocate(s_name)
deallocate(s_unit)
deallocate(s_desc)
nvars = get_nvars(file_in)
allocate(s_name(nvars), s_unit(nvars), s_desc(nvars))
call getAttributes(file_in, nvars, s_name, s_desc, s_unit)
do jid=1, 64 ! CAR*
    call write_array(nunit, NA1, CAR(1:NA1, jid), s_name(jid), s_unit(jid), s_desc(jid))
enddo

! Sparse profiles

jid = jid + 1
call write_array(nunit, NA1,  AIMPT(1:NA1), s_name(jid), s_unit(jid), s_desc(jid))
jid = jid + 1
call write_array(nunit, NA1,  AMAIN(1:NA1), s_name(jid), s_unit(jid), s_desc(jid))
jid = jid + 1
call write_array(nunit, NA1,  AREAT(1:NA1), s_name(jid), s_unit(jid), s_desc(jid))
jid = jid + 1
call write_array(nunit, NA1,  B0DB2(1:NA1), s_name(jid), s_unit(jid), s_desc(jid))
jid = jid + 1
call write_array(nunit, NA1,   BDB0(1:NA1), s_name(jid), s_unit(jid), s_desc(jid))
jid = jid + 1
call write_array(nunit, NA1,  BDB02(1:NA1), s_name(jid), s_unit(jid), s_desc(jid))
jid = jid + 1
call write_array(nunit, NA1,  BMAXT(1:NA1), s_name(jid), s_unit(jid), s_desc(jid))
jid = jid + 1
call write_array(nunit, NA1, BMINT (1:NA1), s_name(jid), s_unit(jid), s_desc(jid))
jid=jid + 1
call write_array(nunit, NA1,     CC(1:NA1), s_name(jid), s_unit(jid), s_desc(jid))
jid = jid + 1
call write_array(nunit, NA1,     CD(1:NA1), s_name(jid), s_unit(jid), s_desc(jid))
jid = jid + 1
call write_array(nunit, NA1,     CE(1:NA1), s_name(jid), s_unit(jid), s_desc(jid))
jid = jid + 1
call write_array(nunit, NA1,     CI(1:NA1), s_name(jid), s_unit(jid), s_desc(jid))
jid = jid + 1
call write_array(nunit, NA1,     CN(1:NA1), s_name(jid), s_unit(jid), s_desc(jid))
jid = jid + 1
call write_array(nunit, NA1,  CNPAD(1:NA1), s_name(jid), s_unit(jid), s_desc(jid))
jid = jid + 1
call write_array(nunit, NA1,  CNPAP(1:NA1), s_name(jid), s_unit(jid), s_desc(jid))
jid = jid + 1
call write_array(nunit, NA1,  CNPAR(1:NA1), s_name(jid), s_unit(jid), s_desc(jid))
jid = jid + 1
call write_array(nunit, NA1,     CU(1:NA1), s_name(jid), s_unit(jid), s_desc(jid))
jid = jid + 1
call write_array(nunit, NA1,   CUBM(1:NA1), s_name(jid), s_unit(jid), s_desc(jid))
jid = jid + 1
call write_array(nunit, NA1,   CUBS(1:NA1), s_name(jid), s_unit(jid), s_desc(jid))
jid = jid + 1
call write_array(nunit, NA1,  CUECR(1:NA1), s_name(jid), s_unit(jid), s_desc(jid))
jid = jid + 1
call write_array(nunit, NA1,   CUFI(1:NA1), s_name(jid), s_unit(jid), s_desc(jid))
jid = jid + 1
call write_array(nunit, NA1,   CUFW(1:NA1), s_name(jid), s_unit(jid), s_desc(jid))
jid = jid + 1
call write_array(nunit, NA1,  CUICR(1:NA1), s_name(jid), s_unit(jid), s_desc(jid))
jid = jid + 1
call write_array(nunit, NA1,   CULH(1:NA1), s_name(jid), s_unit(jid), s_desc(jid))
jid = jid + 1
call write_array(nunit, NA1,  CUTOR(1:NA1), s_name(jid), s_unit(jid), s_desc(jid))
jid = jid + 1
call write_array(nunit, NA1,     CV(1:NA1), s_name(jid), s_unit(jid), s_desc(jid))
jid = jid + 1
call write_array(nunit, NA1,     DC(1:NA1), s_name(jid), s_unit(jid), s_desc(jid))
jid = jid + 1
call write_array(nunit, NA1,     DN(1:NA1), s_name(jid), s_unit(jid), s_desc(jid))
jid = jid + 1
call write_array(nunit, NA1,  DDNEO(1:NA1), s_name(jid), s_unit(jid), s_desc(jid))
jid = jid + 1
call write_array(nunit, NA1, DDNEOD(1:NA1), s_name(jid), s_unit(jid), s_desc(jid))
jid = jid + 1
call write_array(nunit, NA1,  DIMP1(1:NA1), s_name(jid), s_unit(jid), s_desc(jid))
jid = jid + 1
call write_array(nunit, NA1,  DIMP2(1:NA1), s_name(jid), s_unit(jid), s_desc(jid))
jid = jid + 1
call write_array(nunit, NA1,  DIMP3(1:NA1), s_name(jid), s_unit(jid), s_desc(jid))
jid = jid + 1
call write_array(nunit, NA1,  DLNEO(1:NA1), s_name(jid), s_unit(jid), s_desc(jid))
jid = jid + 1
call write_array(nunit, NA1, DLNEOD(1:NA1), s_name(jid), s_unit(jid), s_desc(jid))
jid = jid + 1
call write_array(nunit, NA1,  DRODA(1:NA1), s_name(jid), s_unit(jid), s_desc(jid))
jid = jid + 1
call write_array(nunit, NA1,   ELON(1:NA1), s_name(jid), s_unit(jid), s_desc(jid))
jid = jid + 1
call write_array(nunit, NA1,   EQFF(1:NA1), s_name(jid), s_unit(jid), s_desc(jid))
jid = jid + 1
call write_array(nunit, NA1,   EQPF(1:NA1), s_name(jid), s_unit(jid), s_desc(jid))
jid = jid + 1
call write_array(nunit, NA1,     ER(1:NA1), s_name(jid), s_unit(jid), s_desc(jid))
jid = jid + 1
call write_array(nunit, NA1,     F0(1:NA1), s_name(jid), s_unit(jid), s_desc(jid))
jid = jid + 1
call write_array(nunit, NA1,    F0O(1:NA1), s_name(jid), s_unit(jid), s_desc(jid))
jid = jid + 1
call write_array(nunit, NA1,     F1(1:NA1), s_name(jid), s_unit(jid), s_desc(jid))
jid = jid + 1
call write_array(nunit, NA1,    F1O(1:NA1), s_name(jid), s_unit(jid), s_desc(jid))
jid = jid + 1
call write_array(nunit, NA1,     F2(1:NA1), s_name(jid), s_unit(jid), s_desc(jid))
jid = jid + 1
call write_array(nunit, NA1,    F2O(1:NA1), s_name(jid), s_unit(jid), s_desc(jid))
jid = jid + 1
call write_array(nunit, NA1,     F3(1:NA1), s_name(jid), s_unit(jid), s_desc(jid))
jid = jid + 1
call write_array(nunit, NA1,    F3O(1:NA1), s_name(jid), s_unit(jid), s_desc(jid))
jid = jid + 1
call write_array(nunit, NA1,     F4(1:NA1), s_name(jid), s_unit(jid), s_desc(jid))
jid = jid + 1
call write_array(nunit, NA1,    F4O(1:NA1), s_name(jid), s_unit(jid), s_desc(jid))
jid = jid + 1
call write_array(nunit, NA1,     F5(1:NA1), s_name(jid), s_unit(jid), s_desc(jid))
jid = jid + 1
call write_array(nunit, NA1,    F5O(1:NA1), s_name(jid), s_unit(jid), s_desc(jid))
jid = jid + 1
call write_array(nunit, NA1,     F6(1:NA1), s_name(jid), s_unit(jid), s_desc(jid))
jid = jid + 1
call write_array(nunit, NA1,    F6O(1:NA1), s_name(jid), s_unit(jid), s_desc(jid))
jid = jid + 1
call write_array(nunit, NA1,     F7(1:NA1), s_name(jid), s_unit(jid), s_desc(jid))
jid = jid + 1
call write_array(nunit, NA1,    F7O(1:NA1), s_name(jid), s_unit(jid), s_desc(jid))
jid = jid + 1
call write_array(nunit, NA1,     F8(1:NA1), s_name(jid), s_unit(jid), s_desc(jid))
jid = jid + 1
call write_array(nunit, NA1,    F8O(1:NA1), s_name(jid), s_unit(jid), s_desc(jid))
jid = jid + 1
call write_array(nunit, NA1,     F9(1:NA1), s_name(jid), s_unit(jid), s_desc(jid))
jid = jid + 1
call write_array(nunit, NA1,    F9O(1:NA1), s_name(jid), s_unit(jid), s_desc(jid))
jid = jid + 1
call write_array(nunit, NA1,   FOFB(1:NA1), s_name(jid), s_unit(jid), s_desc(jid))
jid = jid + 1
call write_array(nunit, NA1,     FP(1:NA1), s_name(jid), s_unit(jid), s_desc(jid))
jid = jid + 1
call write_array(nunit, NA1,    FPO(1:NA1), s_name(jid), s_unit(jid), s_desc(jid))
jid = jid + 1
call write_array(nunit, NA1,FP_NORM(1:NA1), s_name(jid), s_unit(jid), s_desc(jid))
jid = jid + 1
call write_array(nunit, NA1,     FV(1:NA1), s_name(jid), s_unit(jid), s_desc(jid))
jid = jid + 1
call write_array(nunit, NA1,    G11(1:NA1), s_name(jid), s_unit(jid), s_desc(jid))
jid = jid + 1
call write_array(nunit, NA1,    G22(1:NA1), s_name(jid), s_unit(jid), s_desc(jid))
jid = jid + 1
call write_array(nunit, NA1,   G22E(1:NA1), s_name(jid), s_unit(jid), s_desc(jid))
jid = jid + 1
call write_array(nunit, NA1,    G33(1:NA1), s_name(jid), s_unit(jid), s_desc(jid))
jid = jid + 1
call write_array(nunit, NA1,   G33E(1:NA1), s_name(jid), s_unit(jid), s_desc(jid))
jid = jid + 1
call write_array(nunit, NA1,    G41(1:NA1), s_name(jid), s_unit(jid), s_desc(jid))
jid = jid + 1
call write_array(nunit, NA1,    G42(1:NA1), s_name(jid), s_unit(jid), s_desc(jid))
jid = jid + 1
call write_array(nunit, NA1,    G43(1:NA1), s_name(jid), s_unit(jid), s_desc(jid))
jid = jid + 1
call write_array(nunit, NA1,    G44(1:NA1), s_name(jid), s_unit(jid), s_desc(jid))
jid = jid + 1
call write_array(nunit, NA1,    G45(1:NA1), s_name(jid), s_unit(jid), s_desc(jid))
jid = jid + 1
call write_array(nunit, NA1,     GN(1:NA1), s_name(jid), s_unit(jid), s_desc(jid))
jid = jid + 1
call write_array(nunit, NA1, GRADRO(1:NA1), s_name(jid), s_unit(jid), s_desc(jid))
jid = jid + 1
call write_array(nunit, NA1,     HC(1:NA1), s_name(jid), s_unit(jid), s_desc(jid))
jid = jid + 1
call write_array(nunit, NA1,     HE(1:NA1), s_name(jid), s_unit(jid), s_desc(jid))
jid = jid + 1
call write_array(nunit, NA1,   IPOL(1:NA1), s_name(jid), s_unit(jid), s_desc(jid))
jid = jid + 1
call write_array(nunit, NA1,   MRHO(1:NA1), s_name(jid), s_unit(jid), s_desc(jid))
jid = jid + 1
call write_array(nunit, NA1,     MU(1:NA1), s_name(jid), s_unit(jid), s_desc(jid))
jid = jid + 1
call write_array(nunit, NA1,     MV(1:NA1), s_name(jid), s_unit(jid), s_desc(jid))
jid = jid + 1
call write_array(nunit, NA1,   NALF(1:NA1), s_name(jid), s_unit(jid), s_desc(jid))
jid = jid + 1
call write_array(nunit, NA1,  NDEUT(1:NA1), s_name(jid), s_unit(jid), s_desc(jid))
jid = jid + 1
call write_array(nunit, NA1,     NE(1:NA1), s_name(jid), s_unit(jid), s_desc(jid))
jid = jid + 1
call write_array(nunit, NA1,    NEO(1:NA1), s_name(jid), s_unit(jid), s_desc(jid))
jid = jid + 1
call write_array(nunit, NA1,   NHE3(1:NA1), s_name(jid), s_unit(jid), s_desc(jid))
jid = jid + 1
call write_array(nunit, NA1,  NHYDR(1:NA1), s_name(jid), s_unit(jid), s_desc(jid))
jid = jid + 1
call write_array(nunit, NA1,     NI(1:NA1), s_name(jid), s_unit(jid), s_desc(jid))
jid = jid + 1
call write_array(nunit, NA1,   NIBM(1:NA1), s_name(jid), s_unit(jid), s_desc(jid))
jid = jid + 1
call write_array(nunit, NA1,  NIMPT(1:NA1), s_name(jid), s_unit(jid), s_desc(jid))
jid = jid + 1
call write_array(nunit, NA1,    NIO(1:NA1), s_name(jid), s_unit(jid), s_desc(jid))
jid = jid + 1
call write_array(nunit, NA1,   NIZ1(1:NA1), s_name(jid), s_unit(jid), s_desc(jid))
jid = jid + 1
call write_array(nunit, NA1,   NIZ2(1:NA1), s_name(jid), s_unit(jid), s_desc(jid))
jid = jid + 1
call write_array(nunit, NA1,   NIZ3(1:NA1), s_name(jid), s_unit(jid), s_desc(jid))
jid = jid + 1
call write_array(nunit, NA1,  NMAIN(1:NA1), s_name(jid), s_unit(jid), s_desc(jid))
jid = jid + 1
call write_array(nunit, NA1,     NN(1:NA1), s_name(jid), s_unit(jid), s_desc(jid))
jid = jid + 1
call write_array(nunit, NA1,  NNBM1(1:NA1), s_name(jid), s_unit(jid), s_desc(jid))
jid = jid + 1
call write_array(nunit, NA1,  NNBM2(1:NA1), s_name(jid), s_unit(jid), s_desc(jid))
jid = jid + 1
call write_array(nunit, NA1,  NNBM3(1:NA1), s_name(jid), s_unit(jid), s_desc(jid))
jid = jid + 1
call write_array(nunit, NA1,  NTRIT(1:NA1), s_name(jid), s_unit(jid), s_desc(jid))
jid = jid + 1
call write_array(nunit, NA1,  PBEAM(1:NA1), s_name(jid), s_unit(jid), s_desc(jid))
jid = jid + 1
call write_array(nunit, NA1,  PBLON(1:NA1), s_name(jid), s_unit(jid), s_desc(jid))
jid = jid + 1
call write_array(nunit, NA1,  PBOL1(1:NA1), s_name(jid), s_unit(jid), s_desc(jid))
jid = jid + 1
call write_array(nunit, NA1,  PBOL2(1:NA1), s_name(jid), s_unit(jid), s_desc(jid))
jid = jid + 1
call write_array(nunit, NA1,  PBOL3(1:NA1), s_name(jid), s_unit(jid), s_desc(jid))
jid = jid + 1
call write_array(nunit, NA1,  PBPER(1:NA1), s_name(jid), s_unit(jid), s_desc(jid))
jid = jid + 1
call write_array(nunit, NA1,    PDE(1:NA1), s_name(jid), s_unit(jid), s_desc(jid))
jid = jid + 1
call write_array(nunit, NA1,    PDI(1:NA1), s_name(jid), s_unit(jid), s_desc(jid))
jid = jid + 1
call write_array(nunit, NA1,     PE(1:NA1), s_name(jid), s_unit(jid), s_desc(jid))
jid = jid + 1
call write_array(nunit, NA1,   PEBM(1:NA1), s_name(jid), s_unit(jid), s_desc(jid))
jid = jid + 1
call write_array(nunit, NA1,  PEECR(1:NA1), s_name(jid), s_unit(jid), s_desc(jid))
jid = jid + 1
call write_array(nunit, NA1,   PEFW(1:NA1), s_name(jid), s_unit(jid), s_desc(jid))
jid = jid + 1
call write_array(nunit, NA1,  PEICR(1:NA1), s_name(jid), s_unit(jid), s_desc(jid))
jid = jid + 1
call write_array(nunit, NA1,  PEIQI(1:NA1), s_name(jid), s_unit(jid), s_desc(jid))
jid = jid + 1
call write_array(nunit, NA1,   PELH(1:NA1), s_name(jid), s_unit(jid), s_desc(jid))
jid = jid + 1
call write_array(nunit, NA1,  PELON(1:NA1), s_name(jid), s_unit(jid), s_desc(jid))
jid = jid + 1
call write_array(nunit, NA1,  PEPER(1:NA1), s_name(jid), s_unit(jid), s_desc(jid))
jid = jid + 1
call write_array(nunit, NA1,  PERIM(1:NA1), s_name(jid), s_unit(jid), s_desc(jid))
jid = jid + 1
call write_array(nunit, NA1,  PETOT(1:NA1), s_name(jid), s_unit(jid), s_desc(jid))
jid = jid + 1
call write_array(nunit, NA1,  PFAST(1:NA1), s_name(jid), s_unit(jid), s_desc(jid))
jid = jid + 1
call write_array(nunit, NA1,     PI(1:NA1), s_name(jid), s_unit(jid), s_desc(jid))
jid = jid + 1
call write_array(nunit, NA1,   PIBM(1:NA1), s_name(jid), s_unit(jid), s_desc(jid))
jid = jid + 1
call write_array(nunit, NA1,   PIFW(1:NA1), s_name(jid), s_unit(jid), s_desc(jid))
jid = jid + 1
call write_array(nunit, NA1,  PIICR(1:NA1), s_name(jid), s_unit(jid), s_desc(jid))
jid = jid + 1
call write_array(nunit, NA1,  PITOT(1:NA1), s_name(jid), s_unit(jid), s_desc(jid))
jid = jid + 1
call write_array(nunit, NA1,   PRAD(1:NA1), s_name(jid), s_unit(jid), s_desc(jid))
jid = jid + 1
call write_array(nunit, NA1,   PRES(1:NA1), s_name(jid), s_unit(jid), s_desc(jid))
jid = jid + 1
call write_array(nunit, NA1,  PSXR1(1:NA1), s_name(jid), s_unit(jid), s_desc(jid))
jid = jid + 1
call write_array(nunit, NA1,  PSXR2(1:NA1), s_name(jid), s_unit(jid), s_desc(jid))
jid = jid + 1
call write_array(nunit, NA1,  PSXR3(1:NA1), s_name(jid), s_unit(jid), s_desc(jid))
jid = jid + 1
call write_array(nunit, NA1,     QE(1:NA1), s_name(jid), s_unit(jid), s_desc(jid))
jid = jid + 1
call write_array(nunit, NA1,    QF0(1:NA1), s_name(jid), s_unit(jid), s_desc(jid))
jid = jid + 1
call write_array(nunit, NA1,    QF1(1:NA1), s_name(jid), s_unit(jid), s_desc(jid))
jid = jid + 1
call write_array(nunit, NA1,    QF2(1:NA1), s_name(jid), s_unit(jid), s_desc(jid))
jid = jid + 1
call write_array(nunit, NA1,    QF3(1:NA1), s_name(jid), s_unit(jid), s_desc(jid))
jid = jid + 1
call write_array(nunit, NA1,    QF4(1:NA1), s_name(jid), s_unit(jid), s_desc(jid))
jid = jid + 1
call write_array(nunit, NA1,    QF5(1:NA1), s_name(jid), s_unit(jid), s_desc(jid))
jid = jid + 1
call write_array(nunit, NA1,    QF6(1:NA1), s_name(jid), s_unit(jid), s_desc(jid))
jid = jid + 1
call write_array(nunit, NA1,    QF7(1:NA1), s_name(jid), s_unit(jid), s_desc(jid))
jid = jid + 1
call write_array(nunit, NA1,    QF8(1:NA1), s_name(jid), s_unit(jid), s_desc(jid))
jid = jid + 1
call write_array(nunit, NA1,    QF9(1:NA1), s_name(jid), s_unit(jid), s_desc(jid))
jid = jid + 1
call write_array(nunit, NA1,     QI(1:NA1), s_name(jid), s_unit(jid), s_desc(jid))
jid = jid + 1
call write_array(nunit, NA1,     QN(1:NA1), s_name(jid), s_unit(jid), s_desc(jid))
jid = jid + 1
call write_array(nunit, NA1,     QU(1:NA1), s_name(jid), s_unit(jid), s_desc(jid))
jid = jid + 1
call write_array(nunit, NA1,    RHO(1:NA1), s_name(jid), s_unit(jid), s_desc(jid))
jid = jid + 1
call write_array(nunit, NA1,RHO_POL(1:NA1), s_name(jid), s_unit(jid), s_desc(jid))
jid = jid + 1
call write_array(nunit, NA1,  RUPAR(1:NA1), s_name(jid), s_unit(jid), s_desc(jid))
jid = jid + 1
call write_array(nunit, NA1,  RUPFR(1:NA1), s_name(jid), s_unit(jid), s_desc(jid))
jid = jid + 1
call write_array(nunit, NA1,  RUPYR(1:NA1), s_name(jid), s_unit(jid), s_desc(jid))
jid = jid + 1
call write_array(nunit, NA1,  SCUBM(1:NA1), s_name(jid), s_unit(jid), s_desc(jid))
jid = jid + 1
call write_array(nunit, NA1,    SD0(1:NA1), s_name(jid), s_unit(jid), s_desc(jid))
jid = jid + 1
call write_array(nunit, NA1,    SD1(1:NA1), s_name(jid), s_unit(jid), s_desc(jid))
jid = jid + 1
call write_array(nunit, NA1,    SD2(1:NA1), s_name(jid), s_unit(jid), s_desc(jid))
jid = jid + 1
call write_array(nunit, NA1,    SD3(1:NA1), s_name(jid), s_unit(jid), s_desc(jid))
jid = jid + 1
call write_array(nunit, NA1,    SD4(1:NA1), s_name(jid), s_unit(jid), s_desc(jid))
jid = jid + 1
call write_array(nunit, NA1,    SD5(1:NA1), s_name(jid), s_unit(jid), s_desc(jid))
jid = jid + 1
call write_array(nunit, NA1,    SD6(1:NA1), s_name(jid), s_unit(jid), s_desc(jid))
jid = jid + 1
call write_array(nunit, NA1,    SD7(1:NA1), s_name(jid), s_unit(jid), s_desc(jid))
jid = jid + 1
call write_array(nunit, NA1,    SD8(1:NA1), s_name(jid), s_unit(jid), s_desc(jid))
jid = jid + 1
call write_array(nunit, NA1,    SD9(1:NA1), s_name(jid), s_unit(jid), s_desc(jid))
jid = jid + 1
call write_array(nunit, NA1,    SDN(1:NA1), s_name(jid), s_unit(jid), s_desc(jid))
jid = jid + 1
call write_array(nunit, NA1, SF0TOT(1:NA1), s_name(jid), s_unit(jid), s_desc(jid))
jid = jid + 1
call write_array(nunit, NA1, SF1TOT(1:NA1), s_name(jid), s_unit(jid), s_desc(jid))
jid = jid + 1
call write_array(nunit, NA1, SF2TOT(1:NA1), s_name(jid), s_unit(jid), s_desc(jid))
jid = jid + 1
call write_array(nunit, NA1, SF3TOT(1:NA1), s_name(jid), s_unit(jid), s_desc(jid))
jid = jid + 1
call write_array(nunit, NA1, SF4TOT(1:NA1), s_name(jid), s_unit(jid), s_desc(jid))
jid = jid + 1
call write_array(nunit, NA1, SF5TOT(1:NA1), s_name(jid), s_unit(jid), s_desc(jid))
jid = jid + 1
call write_array(nunit, NA1, SF6TOT(1:NA1), s_name(jid), s_unit(jid), s_desc(jid))
jid = jid + 1
call write_array(nunit, NA1, SF7TOT(1:NA1), s_name(jid), s_unit(jid), s_desc(jid))
jid = jid + 1
call write_array(nunit, NA1, SF8TOT(1:NA1), s_name(jid), s_unit(jid), s_desc(jid))
jid = jid + 1
call write_array(nunit, NA1, SF9TOT(1:NA1), s_name(jid), s_unit(jid), s_desc(jid))
jid = jid + 1
call write_array(nunit, NA1,  SGNEO(1:NA1), s_name(jid), s_unit(jid), s_desc(jid))
jid = jid + 1
call write_array(nunit, NA1, SGNEOD(1:NA1), s_name(jid), s_unit(jid), s_desc(jid))
jid = jid + 1
call write_array(nunit, NA1,  SHEAR(1:NA1), s_name(jid), s_unit(jid), s_desc(jid))
jid = jid + 1
call write_array(nunit, NA1,   SHIF(1:NA1), s_name(jid), s_unit(jid), s_desc(jid))
jid = jid + 1
call write_array(nunit, NA1,   SHIV(1:NA1), s_name(jid), s_unit(jid), s_desc(jid))
jid = jid + 1
call write_array(nunit, NA1,   SLAT(1:NA1), s_name(jid), s_unit(jid), s_desc(jid))
jid = jid + 1
call write_array(nunit, NA1,     SN(1:NA1), s_name(jid), s_unit(jid), s_desc(jid))
jid = jid + 1
call write_array(nunit, NA1,  SNEBM(1:NA1), s_name(jid), s_unit(jid), s_desc(jid))
jid = jid + 1
call write_array(nunit, NA1, SNIBM1(1:NA1), s_name(jid), s_unit(jid), s_desc(jid))
jid = jid + 1
call write_array(nunit, NA1, SNIBM2(1:NA1), s_name(jid), s_unit(jid), s_desc(jid))
jid = jid + 1
call write_array(nunit, NA1, SNIBM3(1:NA1), s_name(jid), s_unit(jid), s_desc(jid))
jid = jid + 1
call write_array(nunit, NA1,  SNNBM(1:NA1), s_name(jid), s_unit(jid), s_desc(jid))
jid = jid + 1
call write_array(nunit, NA1,  SNTOT(1:NA1), s_name(jid), s_unit(jid), s_desc(jid))
jid = jid + 1
call write_array(nunit, NA1,  SQEPS(1:NA1), s_name(jid), s_unit(jid), s_desc(jid))
jid = jid + 1
call write_array(nunit, NA1, SQUARN(1:NA1), s_name(jid), s_unit(jid), s_desc(jid))
jid = jid + 1
call write_array(nunit, NA1,   SRHO(1:NA1), s_name(jid), s_unit(jid), s_desc(jid))
jid = jid + 1
call write_array(nunit, NA1,   SXHO(1:NA1), s_name(jid), s_unit(jid), s_desc(jid))
jid = jid + 1
call write_array(nunit, NA1,     TE(1:NA1), s_name(jid), s_unit(jid), s_desc(jid))
jid = jid + 1
call write_array(nunit, NA1,    TEO(1:NA1), s_name(jid), s_unit(jid), s_desc(jid))
jid = jid + 1
call write_array(nunit, NA1,     TI(1:NA1), s_name(jid), s_unit(jid), s_desc(jid))
jid = jid + 1
call write_array(nunit, NA1,    TIO(1:NA1), s_name(jid), s_unit(jid), s_desc(jid))
jid = jid + 1
call write_array(nunit, NA1,     TN(1:NA1), s_name(jid), s_unit(jid), s_desc(jid))
jid = jid + 1
call write_array(nunit, NA1,   TRIA(1:NA1), s_name(jid), s_unit(jid), s_desc(jid))
jid = jid + 1
call write_array(nunit, NA1,   TTRQ(1:NA1), s_name(jid), s_unit(jid), s_desc(jid))
jid = jid + 1
call write_array(nunit, NA1,  TTRQI(1:NA1), s_name(jid), s_unit(jid), s_desc(jid))
jid = jid + 1
call write_array(nunit, NA1,   ULON(1:NA1), s_name(jid), s_unit(jid), s_desc(jid))
jid = jid + 1
call write_array(nunit, NA1,   UPAR(1:NA1), s_name(jid), s_unit(jid), s_desc(jid))
jid = jid + 1
call write_array(nunit, NA1,  UPARO(1:NA1), s_name(jid), s_unit(jid), s_desc(jid))
jid = jid + 1
call write_array(nunit, NA1,    UPL(1:NA1), s_name(jid), s_unit(jid), s_desc(jid))
jid = jid + 1
call write_array(nunit, NA1,   UPS0(1:NA1), s_name(jid), s_unit(jid), s_desc(jid))
jid = jid + 1
call write_array(nunit, NA1,  UPS0O(1:NA1), s_name(jid), s_unit(jid), s_desc(jid))
jid = jid + 1
call write_array(nunit, NA1,   UPS1(1:NA1), s_name(jid), s_unit(jid), s_desc(jid))
jid = jid + 1
call write_array(nunit, NA1,  UPS1O(1:NA1), s_name(jid), s_unit(jid), s_desc(jid))
jid = jid + 1
call write_array(nunit, NA1,   UPS2(1:NA1), s_name(jid), s_unit(jid), s_desc(jid))
jid = jid + 1
call write_array(nunit, NA1,  UPS2O(1:NA1), s_name(jid), s_unit(jid), s_desc(jid))
jid = jid + 1
call write_array(nunit, NA1,  VIMP1(1:NA1), s_name(jid), s_unit(jid), s_desc(jid))
jid = jid + 1
call write_array(nunit, NA1,  VIMP2(1:NA1), s_name(jid), s_unit(jid), s_desc(jid))
jid = jid + 1
call write_array(nunit, NA1,  VIMP3(1:NA1), s_name(jid), s_unit(jid), s_desc(jid))
jid = jid + 1
call write_array(nunit, NA1,  VOLUM(1:NA1), s_name(jid), s_unit(jid), s_desc(jid))
jid = jid + 1
call write_array(nunit, NA1,     VP(1:NA1), s_name(jid), s_unit(jid), s_desc(jid))
jid = jid + 1
call write_array(nunit, NA1,   VPFP(1:NA1), s_name(jid), s_unit(jid), s_desc(jid))
jid = jid + 1
call write_array(nunit, NA1,   VPOL(1:NA1), s_name(jid), s_unit(jid), s_desc(jid))
jid = jid + 1
call write_array(nunit, NA1,     VR(1:NA1), s_name(jid), s_unit(jid), s_desc(jid))
jid = jid + 1
call write_array(nunit, NA1,    VRO(1:NA1), s_name(jid), s_unit(jid), s_desc(jid))
jid = jid + 1
call write_array(nunit, NA1,    VRS(1:NA1), s_name(jid), s_unit(jid), s_desc(jid))
jid = jid + 1
call write_array(nunit, NA1,   VTOR(1:NA1), s_name(jid), s_unit(jid), s_desc(jid))
jid = jid + 1
call write_array(nunit, NA1,     XC(1:NA1), s_name(jid), s_unit(jid), s_desc(jid))
jid = jid + 1
call write_array(nunit, NA1,     XI(1:NA1), s_name(jid), s_unit(jid), s_desc(jid))
jid = jid + 1
call write_array(nunit, NA1,   XRHO(1:NA1), s_name(jid), s_unit(jid), s_desc(jid))
jid = jid + 1
call write_array(nunit, NA1,  XUPAD(1:NA1), s_name(jid), s_unit(jid), s_desc(jid))
jid = jid + 1
call write_array(nunit, NA1,  XUPAP(1:NA1), s_name(jid), s_unit(jid), s_desc(jid))
jid = jid + 1
call write_array(nunit, NA1,  XUPAR(1:NA1), s_name(jid), s_unit(jid), s_desc(jid))
jid = jid + 1
call write_array(nunit, NA1,    ZEF(1:NA1), s_name(jid), s_unit(jid), s_desc(jid))
jid = jid + 1
call write_array(nunit, NA1,   ZEF1(1:NA1), s_name(jid), s_unit(jid), s_desc(jid))
jid = jid + 1
call write_array(nunit, NA1,   ZEF2(1:NA1), s_name(jid), s_unit(jid), s_desc(jid))
jid = jid + 1
call write_array(nunit, NA1,   ZEF3(1:NA1), s_name(jid), s_unit(jid), s_desc(jid))
jid = jid + 1
call write_array(nunit, NA1,   ZIM1(1:NA1), s_name(jid), s_unit(jid), s_desc(jid))
jid = jid + 1
call write_array(nunit, NA1,   ZIM2(1:NA1), s_name(jid), s_unit(jid), s_desc(jid))
jid = jid + 1
call write_array(nunit, NA1,   ZIM3(1:NA1), s_name(jid), s_unit(jid), s_desc(jid))
jid = jid + 1
call write_array(nunit, NA1,  ZIMPT(1:NA1), s_name(jid), s_unit(jid), s_desc(jid))
jid = jid + 1
call write_array(nunit, NA1,  ZMAIN(1:NA1), s_name(jid), s_unit(jid), s_desc(jid))

! Equilibrium 1d profiles


file_in = TRIM(AWD) // '/main/equil_1d.txt'
deallocate(s_name)
deallocate(s_unit)
deallocate(s_desc)
nvars = get_nvars(file_in)
allocate(s_name(nvars), s_unit(nvars), s_desc(nvars))
call getAttributes(file_in, nvars, s_name, s_desc, s_unit)
jid = 1
call write_array(nunit, nrho_surf, equil_now%profiles_1d%phi    , s_name(jid), s_unit(jid), s_desc(jid))
jid = 2
call write_array(nunit, nrho_surf, equil_now%profiles_1d%pprime , s_name(jid), s_unit(jid), s_desc(jid))
jid = 3
call write_array(nunit, nrho_surf, equil_now%profiles_1d%ffprime, s_name(jid), s_unit(jid), s_desc(jid))

file_in = TRIM(AWD) // '/main/equil_2d.txt'
ndim = nrho_surf*nthe_surf
deallocate(s_name)
deallocate(s_unit)
deallocate(s_desc)
nvars = get_nvars(file_in)
allocate(s_name(nvars), s_unit(nvars), s_desc(nvars))
call getAttributes(file_in, nvars, s_name, s_desc, s_unit)
jid = 1
call write_array(nunit, ndim, equil_now%coord_sys%position%r, s_name(jid), s_unit(jid), s_desc(jid))
jid = 2
call write_array(nunit, ndim, equil_now%coord_sys%position%z, s_name(jid), s_unit(jid), s_desc(jid))
jid = 3
call write_array(nunit, ndim, equil_now%coord_sys%position%psirz, s_name(jid), s_unit(jid), s_desc(jid))

call write_array(nunit, nrho_surf, equil_now%profiles_1d%rho_tor, 'RHO_SURF', '-', 'rho toroidal')
call write_array(nunit, NA1, equil_now%coord_sys%position%teta2d, 'THETA', 'rad', 'Pol. angle')

write(nunit, '(A)') '    "THETA": {"units": "rad", "long_name": "Pol. angle", "data": ['
write(nunit, '(5(es15.8, ","))') (equil_now%coord_sys%position%teta2d(jrho), jrho=1, nthe_surf-1)
write(nunit, '(es15.8)') equil_now%coord_sys%position%teta2d(nthe_surf) ! No comma after last array entry

write(nunit, '(A/)') ']}'

!-----------
! Close json
!-----------

write(nunit, '(A)') '}'
close(nunit)
write(*, '(A)') '   Written file ' // json_out

deallocate(s_name)
deallocate(s_unit)
deallocate(s_desc)

j_call = j_call + 1

return
end subroutine a2json

!---------------------------------------------------------------
subroutine write_scalar_block(nunit, file_in, scalar_list)

implicit none

integer, parameter :: l_name=8, l_unit=25, l_desc=60

integer, intent(in) :: nunit
character(len=*), intent(in) :: file_in
double precision, intent(in), dimension(*) :: scalar_list

integer :: nvars, jid
character(len=l_name), allocatable, dimension(:) :: s_name
character(len=l_unit), allocatable, dimension(:) :: s_unit
character(len=l_desc), allocatable, dimension(:) :: s_desc
integer, external :: get_nvars

101 format('    "', A, '": {"units": "', A, '", "long_name": "', A, '", "data": ', es15.8, '},', /)

nvars = get_nvars(file_in)
allocate(s_name(nvars), s_unit(nvars), s_desc(nvars))
call getAttributes(TRIM(file_in), nvars, s_name, s_desc, s_unit)
do jid=1, nvars
    write(nunit, 101) TRIM(s_name(jid)), TRIM(s_unit(jid)), TRIM(s_desc(jid)), scalar_list(jid)
enddo
deallocate(s_name)
deallocate(s_unit)
deallocate(s_desc)

return
end subroutine write_scalar_block

!---------------------------------------------------------------
subroutine write_array(nunit, ndim, arr, sname, sunit, sdesc)

implicit none

integer, parameter :: l_name=8, l_unit=25, l_desc=60

integer, intent(in) :: nunit, ndim
double precision, intent(in), dimension(ndim) :: arr
character(len=*), intent(in) :: sname, sunit, sdesc

integer :: i

102 format('    "', A, '": {"units": "', A, '", "long_name": "', A, '", "data": [')
write(nunit, 102) TRIM(sname), TRIM(sunit), TRIM(sdesc)
if (MAXVAL(ABS(arr)) > 0.) then
    write(nunit, '(5(es15.8, ","))') (arr(i), i=1, ndim-1)
    write(nunit, '(es15.8)') arr(ndim) ! No comma after last array entry
endif
write(nunit, '(A/)') ']},'

return
end subroutine write_array

!---------------------------------------------------------------
integer function get_nvars(file_in)

implicit none

integer, parameter :: nunit=31

character(len=*), intent(in) :: file_in

integer :: ios

get_nvars = 0
open(nunit, file=TRIM(file_in), iostat=ios)
read(nunit, '(/A)')
do
    read(nunit, '(A)', iostat=ios)
    if (ios /= 0) EXIT
    get_nvars = get_nvars + 1
enddo
close(nunit)

return
end function get_nvars

!---------------------------------------------------------------
subroutine getAttributes(file_in, nvars, s_name, s_desc, s_unit)

implicit none


integer, parameter :: nunit=31, l_name=8, l_unit=25, l_desc=60

integer, intent(in) :: nvars
character(len=*), intent(in) :: file_in
character(len=l_name), intent(out), dimension(nvars) :: s_name
character(len=l_desc), intent(out), dimension(nvars) :: s_desc
character(len=l_unit), intent(out), dimension(nvars) :: s_unit

character(len=l_name) :: sname
character(len=l_desc) :: sdesc
character(len=l_unit) :: sunit

integer :: ios, varid

varid = 0
open(nunit, file=TRIM(file_in), iostat=ios)
read(nunit, '(/A)')
do
    read(nunit, '(A8, X, A25, X, A60)', iostat=ios) sname, sunit, sdesc
    if (ios /= 0) EXIT
    varid = varid + 1
    s_name(varid) = sname
    s_unit(varid) = sunit
    s_desc(varid) = sdesc
enddo
close(nunit)

return
end subroutine getAttributes
