subroutine a2json
  ! Please do not edit this file, nor take a copy from a different commit of the git repo
  
use parameters_a2equil, only: equil_now
use parameter_inc
use const_inc
use status_inc
use outcmn_inc, only: AWD, exp_file, equ_file

implicit none

! NetCDF variables

logical, parameter :: verbose=.True.
integer, parameter :: l_name=8, l_unit=25, l_desc=60, nunit=25

integer :: j, i, k, nvars, ios, j_call=1
character(len=120) :: file_in, f_intern2, f_prof, feq_1d, feq_2d, json_out
character(len=l_name), allocatable, dimension(:) :: s_name
character(len=l_unit), allocatable, dimension(:) :: s_unit
character(len=l_desc), allocatable, dimension(:) :: s_desc
integer, external :: get_nvars

save j_call

! NetCDF output

f_intern2 = TRIM(AWD) // '/main/intern2.txt'
f_prof    = TRIM(AWD) // '/main/profiles.txt'
feq_1d    = TRIM(AWD) // '/main/equil_1d.txt'
feq_2d    = TRIM(AWD) // '/main/equil_2d.txt'

write(json_out, '(5A, i0, A)') TRIM(awd), '/ncdf_out/', TRIM(exp_file), TRIM(equ_file), '-', j_call, '.json'

open(nunit, file=TRIM(json_out), iostat=ios)
write(nunit, '(A\)') '{'

file_in = TRIM(AWD) // '/main/variables.txt'
if (allocated(s_name)) then
    deallocate(s_name)
    deallocate(s_unit)
    deallocate(s_desc)
endif
nvars = get_nvars(file_in)
allocate(s_name(nvars), s_unit(nvars), s_desc(nvars))
call getAttributes(file_in, nvars, s_name, s_desc, s_unit)
do j=1, nvars
    write(nunit, '(7A, es15.8, A)') '    "', TRIM(s_name(j)), '": {"units": "', TRIM(s_unit(j)), &
        '", "long_name": "', TRIM(s_desc(j)), '", "data": ', DEVAR(j), '},'
enddo
write(nunit, '(A)') ''

file_in = TRIM(AWD) // '/main/variables_x.txt'
deallocate(s_name)
deallocate(s_unit)
deallocate(s_desc)
nvars = get_nvars(file_in)
allocate(s_name(nvars), s_unit(nvars), s_desc(nvars))
call getAttributes(file_in, nvars, s_name, s_desc, s_unit)
do j=1, nvars
    write(nunit, '(7A, es15.8, A)') '    "', TRIM(s_name(j)), '": {"units": "', TRIM(s_unit(j)), &
        '", "long_name": "', TRIM(s_desc(j)), '", "data": ', DEVARX(j), '},'
enddo
write(nunit, '(A)') ''

file_in = TRIM(AWD) // '/main/constants.txt'
deallocate(s_name)
deallocate(s_unit)
deallocate(s_desc)
nvars = get_nvars(file_in)
allocate(s_name(nvars), s_unit(nvars), s_desc(nvars))
call getAttributes(file_in, nvars, s_name, s_desc, s_unit)
do j=1, nvars
    write(nunit, '(7A, es15.8, A)') '    "', TRIM(s_name(j)), '": {"units": "', TRIM(s_unit(j)), &
        '", "long_name": "', TRIM(s_desc(j)), '", "data": ', CONSTF(j), '},'
enddo
write(nunit, '(A)') ''

file_in = TRIM(AWD) // '/main/internal.txt'
deallocate(s_name)
deallocate(s_unit)
deallocate(s_desc)
nvars = get_nvars(file_in)
allocate(s_name(nvars), s_unit(nvars), s_desc(nvars))
call getAttributes(file_in, nvars, s_name, s_desc, s_unit)
do j=1, nvars
    write(nunit, '(7A, es15.8, A)') '    "', TRIM(s_name(j)), '": {"units": "', TRIM(s_unit(j)), &
        '", "long_name": "', TRIM(s_desc(j)), '", "data": ', DELOUT(j), '},'
enddo
write(nunit, '(A)') ''

file_in = TRIM(AWD) // '/main/profiles_x.txt'
deallocate(s_name)
deallocate(s_unit)
deallocate(s_desc)
nvars = get_nvars(file_in)
allocate(s_name(nvars), s_unit(nvars), s_desc(nvars))
call getAttributes(file_in, nvars, s_name, s_desc, s_unit)
do j=1, nvars
    write(nunit, '(7A)') '    "', TRIM(s_name(j)), '": {"units": "', TRIM(s_unit(j)), &
         '", "long_name": "', TRIM(s_desc(j)), '", "data": ['
    if (MAXVAL(ABS(EXT(1:NA1, j))) > 0.) then
        write(nunit, '(5(es15.8, ","))') (EXT(i, j), i=1, NA1-1)
        write(nunit, '(es15.8)') EXT(NA1, j) ! No comma after last array entry
     endif
     write(nunit, '(A)') ']},'
enddo

write(nunit, '(A)') '}'
close(nunit)
write(*, '(A)') '   Written file ' // json_out

j_call = j_call + 1

return
end subroutine a2json

!---------------------------------------------------------------
integer function get_nvars(file_in)

implicit none

integer, parameter :: nunit=31

character(len=*), intent(in) :: file_in

integer :: ios

get_nvars = 0
open(nunit, file=TRIM(file_in), iostat=ios)
read(nunit, '(/A)')
do
    read(nunit, '(A)', iostat=ios)
    if (ios /= 0) EXIT
    get_nvars = get_nvars + 1
enddo
close(nunit)

return
end function get_nvars

!---------------------------------------------------------------
subroutine getAttributes(file_in, nvars, s_name, s_desc, s_unit)

implicit none


integer, parameter :: nunit=31, l_name=8, l_unit=25, l_desc=60

integer, intent(in) :: nvars
character(len=*), intent(in) :: file_in
character(len=l_name), intent(out), dimension(nvars) :: s_name
character(len=l_desc), intent(out), dimension(nvars) :: s_desc
character(len=l_unit), intent(out), dimension(nvars) :: s_unit

character(len=l_name) :: sname
character(len=l_desc) :: sdesc
character(len=l_unit) :: sunit

integer :: ios, varid

varid = 0
open(nunit, file=TRIM(file_in), iostat=ios)
read(nunit, '(/A)')
do
    read(nunit, '(A8, X, A25, X, A60)', iostat=ios) sname, sunit, sdesc
    if (ios /= 0) EXIT
    varid = varid + 1
    s_name(varid) = sname
    s_unit(varid) = sunit
    s_desc(varid) = sdesc
enddo
close(nunit)

return
end subroutine getAttributes
