subroutine a2json2
! Please do not edit this file, nor take a copy from a different commit of the git repo

use parameters_a2equil, only: equil_now
use parameter_inc
use const_inc
use status_inc
use outcmn_inc, only: AWD, exp_file, equ_file
use json_module, only : json_file, json_value, json_core, json_ck

implicit none

logical :: found, keyFound
integer :: j_call=1, dict_size, jid
character(len=120) :: file_in, json_out
double precision, allocatable, dimension(:) :: data
type(json_file) :: astra_vars, json_vars
type(json_value), pointer :: astraPointer, dictPointer, &
     varPointer, varxPointer, constPointer, profxPointer 
type(json_core) :: jCore, jCore_out

save j_call

write(*, *) 'Starting a2json', j_call

write(json_out, '(5A, i0, A)') TRIM(awd), '/ncdf_out/', TRIM(exp_file), TRIM(equ_file), '-', j_call, '.json'

!-----------
! Profiles
!-----------

! Exp profiles

file_in = TRIM(AWD) // '/main/astra_variables.json'
call astra_vars%initialize(real_format='ES16.8e3')
call astra_vars%load(filename=file_in)

! In future, do this only once, in read_input!
call astra_vars%get_core(jCore)

call jCore_out%create_object(astraPointer, '')   !create the root

! variables
CALL astra_vars%info('variables', n_children=dict_size)
call astra_vars%get('variables', varPointer, found)
do jid=1, dict_size
    CALL jCore%get_child(varPointer, jid, dictPointer, found)
    call jCore%add(dictPointer, 'data', DEVAR(jid))
enddo

! variables_x
CALL astra_vars%info('variables_x', n_children=dict_size)
call astra_vars%get('variables_x', varxPointer, found)
do jid=1, dict_size
    CALL jCore%get_child(varxPointer, jid, dictPointer, found)
    call jCore%add(dictPointer, 'data', DEVARX(jid))
enddo

! constants
CALL astra_vars%info('constants', n_children=dict_size)
call astra_vars%get('constants', constPointer, found)
!write(*, *) '#const', dict_size
do jid=1, dict_size
    CALL jCore%get_child(constPointer, jid, dictPointer, found)
    call jCore%add(dictPointer, 'data', CONSTF(jid))
enddo

! profiles_x
CALL astra_vars%info('profiles_x', n_children=dict_size)
call astra_vars%get('profiles_x', profxPointer, found)
do jid=1, dict_size
    CALL jCore%get_child(profxPointer, jid, dictPointer, found)
    if (MAXVAL(ABS(EXT(1: NA1, jid))) > 1.e-12) then
        call jCore%add(dictPointer, 'data', EXT(1: NA1, jid))
    endif
enddo
 
write(*, *) 'Debug a2json2 1'

! Add all dictoinaries to output JSON object
call jCore_out%add(astraPointer, varPointer)
write(*, *) 'Debug a2json2 2'
call jCore_out%add(astraPointer, varxPointer)
write(*, *) 'Debug a2json2 3'
call jCore_out%add(astraPointer, constPointer)
call jCore_out%add(astraPointer, profxPointer)
write(*, *) 'Debug a2json2 4'

! Store output file
call jCore_out%print(astraPointer, json_out)
write(*, *) 'Stored file ' // TRIM(json_out)
j_call = j_call + 1

return
end subroutine a2json2
