#!/bin/bash -f

source /etc/profile.d/modules.sh
module purge
module load git # avoids annoying warning

# For compilation
module load intel impi anaconda hdf5-serial netcdf-serial

#export GACODE_ROOT=/afs/ipp/home/g/git/gacode
#export GACODE_PLATFORM=TOKS_IPP # important only for compilation, in $GACODE_ROOT/platform/build

make
