!======================================================================|
subroutine TOQLKI(JS, JE, JSBP)
!----------------------------------------------------------------------|
! Call of this subroutine is created by the Astra compiler
! Parameter JSBP is the ordinal number of the (&:) request in a model.
!           JSBP is generated by the Astra compiler.
!----------------------------------------------------------------------|

implicit none

integer, intent(in) :: JS, JE, JSBP

call to_tra(JS, JE, JSBP)

end subroutine TOQLKI

!======================================================================|
subroutine OTQLKI(JS, JE, JSBP, JSBR)
!----------------------------------------------------------------------|
! Call of this subroutine is created by the Astra compiler
!
! Input: JS is the left grid point
!        JE is the right grid point
! Parameter JSBP is the ordinal number of the (&:) request in a model
! Parameter JSBR is the ordinal number of the (:) request in a model
!           JSBR is needed to store the CPU times used by all 
!              processes and subroutines in a homogeneous way.
!           JSBP and JSBR are generated by the Astra compiler.
!----------------------------------------------------------------------|

use outcmn_inc, only: CPTSBR
use status_inc, only: work

implicit none

integer, intent(in) :: JS, JE, JSBP, JSBR

call ot_tra(JS, JE, JSBP, CPTSBR(JSBR), work(1, 21) )

end subroutine OTQLKI
