subroutine equil_allocate(nr2, nz2, nrplasma, nteta)

use parameters_a2equil, only: equil_now

implicit none

integer, intent(in) :: nr2, nz2, nrplasma, nteta

allocate(equil_now%eqgeometry%boundary%r(nteta))
allocate(equil_now%eqgeometry%boundary%z(nteta))
allocate(equil_now%eqgeometry%rectgrid%r2d(nr2))
allocate(equil_now%eqgeometry%rectgrid%z2d(nz2))
allocate(equil_now%eqgeometry%rectgrid%psirz2d(nr2, nz2))
allocate(equil_now%eqgeometry%rectgrid%fdia2d(nr2, nz2))

allocate(equil_now%coord_sys%position%r(nrplasma, nteta))
allocate(equil_now%coord_sys%position%z(nrplasma, nteta))    
allocate(equil_now%coord_sys%position%teta2d(nteta))    
allocate(equil_now%coord_sys%position%rmin(nrplasma, nteta))    
allocate(equil_now%coord_sys%position%psirz(nrplasma, nteta))    
allocate(equil_now%coord_sys%gradvcell(nrplasma, nteta))
allocate(equil_now%coord_sys%bpcell(nrplasma, nteta))
allocate(equil_now%coord_sys%bcell(nrplasma, nteta))
allocate(equil_now%coord_sys%rcell(nrplasma, nteta))
allocate(equil_now%coord_sys%darea(nrplasma, nteta))
allocate(equil_now%coord_sys%jphi(nrplasma, nteta))

allocate(equil_now%profiles_1d%psi(nrplasma))
allocate(equil_now%profiles_1d%pressure(nrplasma))
allocate(equil_now%profiles_1d%phi(nrplasma))
allocate(equil_now%profiles_1d%pprime(nrplasma))
allocate(equil_now%profiles_1d%ffprime(nrplasma))
allocate(equil_now%profiles_1d%F_dia(nrplasma))
allocate(equil_now%profiles_1d%q(nrplasma))
allocate(equil_now%profiles_1d%gm1(nrplasma))
allocate(equil_now%profiles_1d%gm4(nrplasma))
allocate(equil_now%profiles_1d%gm5(nrplasma))
allocate(equil_now%profiles_1d%gm41(nrplasma))
allocate(equil_now%profiles_1d%rbp_b2(nrplasma))
allocate(equil_now%profiles_1d%bplfs(nrplasma))
allocate(equil_now%profiles_1d%rho_tor(nrplasma) )
allocate(equil_now%profiles_1d%jparallel(nrplasma) )
allocate(equil_now%profiles_1d%sigmapar%value(nrplasma) )
allocate(equil_now%profiles_1d%jni%value(nrplasma) )
allocate(equil_now%profiles_1d%te%value(nrplasma) )
allocate(equil_now%profiles_1d%acosB2a(nrplasma, 5))
allocate(equil_now%profiles_1d%asinB2a(nrplasma, 5))
allocate(equil_now%profiles_1d%acosBlnBa(nrplasma, 5))
allocate(equil_now%profiles_1d%asinBlnBa(nrplasma, 5))
allocate(equil_now%profiles_1d%g1(nrplasma))
allocate(equil_now%profiles_1d%g2(nrplasma))
allocate(equil_now%profiles_1d%g2int(nrplasma))
allocate(equil_now%profiles_1d%fofb(nrplasma))
allocate(equil_now%profiles_1d%areat(nrplasma))
allocate(equil_now%profiles_1d%perim(nrplasma))
allocate(equil_now%profiles_1d%ggradro(nrplasma))
allocate(equil_now%profiles_1d%gdroda(nrplasma))
allocate(equil_now%profiles_1d%bmaxt(nrplasma))
allocate(equil_now%profiles_1d%bmint(nrplasma))
allocate(equil_now%profiles_1d%bdb0(nrplasma))
allocate(equil_now%profiles_1d%dPSIdV(nrplasma))
allocate(equil_now%profiles_1d%surface(nrplasma))
allocate(equil_now%profiles_1d%volume(nrplasma))
allocate(equil_now%profiles_1d%r_inboard(nrplasma))
allocate(equil_now%profiles_1d%r_outboard(nrplasma))
allocate(equil_now%profiles_1d%elongation(nrplasma))
allocate(equil_now%profiles_1d%tria_upper(nrplasma))
allocate(equil_now%profiles_1d%tria_lower(nrplasma))
allocate(equil_now%profiles_1d%shif(nrplasma))
allocate(equil_now%profiles_1d%shiv(nrplasma))
allocate(equil_now%profiles_1d%squareness(nrplasma))

return
end subroutine equil_allocate
