/* Generated by Flight-Simulator (common/astra/sbr/Makefile).
   Do not modify this file.  Changes will be overwritten. */
#include <errno.h>
#include <error.h>
#include <fcntl.h>
#include <semaphore.h>
#include <stdarg.h>
#include <stddef.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/mman.h>
#include <sys/stat.h>
#include <sys/types.h>
#include <unistd.h>
struct IPC {
  sem_t *semOwnedByFenix;
  sem_t *semOwnedByAstra;
  char *nameSemOwnedByFenix;
  char *nameSemOwnedByAstra;
  char *nameShmF2A;
  char *nameShmA2F;
};
static
void initIPC(struct IPC *p);
static
char* generateIPCFileNames(struct IPC*, pid_t pid);
static
void destroyIPC(struct IPC *p);
static
void unlinkIpcFiles(struct IPC *p);
struct ShmHeader {
  uint32_t magic;
  uint32_t version;
  size_t totalBytes;
  size_t offsetBytes;
  size_t nPort;
  size_t padding;
};
static
double *shmArrayBase(void *data);
static
size_t *shmWidthBase(void *data);
 void shmr_(double *first, ...);
 void shmw_(double *first, ...);
static
void initIPC(struct IPC *p) {
  memset(p, 0, sizeof(struct IPC));
  p->semOwnedByFenix = SEM_FAILED;
  p->semOwnedByAstra = SEM_FAILED;
}
static void freeNullifyAllIpcFilenames(struct IPC *p) {
  if (p->nameSemOwnedByFenix) { free(p->nameSemOwnedByFenix); p->nameSemOwnedByFenix = NULL; };
  if (p->nameSemOwnedByAstra) { free(p->nameSemOwnedByAstra); p->nameSemOwnedByAstra = NULL; };
  if (p->nameShmF2A) { free(p->nameShmF2A); p->nameShmF2A = NULL; };
  if (p->nameShmA2F) { free(p->nameShmA2F); p->nameShmA2F = NULL; };
}
static char* generateName(pid_t pid, const char* str) {
  char *name = NULL;
  int len;
  len = 1 + snprintf(NULL, 0, "%d.%s", pid, str);
  if (len > 0) {
    name = (char *)malloc(len);
    if (name) {
      snprintf(name, len, "%d.%s", pid, str);
    }
  }
  return name;
}
static
char* generateIPCFileNames(struct IPC *p, pid_t pid) {
  char *err = NULL;
  freeNullifyAllIpcFilenames(p);
  if (pid <= 0) {
    err = "invalid PID for the SEM and SHM names";
  } else {
    p->nameSemOwnedByFenix = generateName(pid, "fenix");
    p->nameSemOwnedByAstra = generateName(pid, "astra");
    p->nameShmF2A = generateName(pid, "fenix2astra");
    p->nameShmA2F = generateName(pid, "astra2fenix");
    if (!(p->nameSemOwnedByFenix
       && p->nameSemOwnedByAstra
       && p->nameShmF2A
       && p->nameShmA2F)) {
      freeNullifyAllIpcFilenames(p);
      err = "fail to allocate memory";
    }
  }
  return err;
}
static
void destroyIPC(struct IPC *p) {
  if ((p->semOwnedByFenix) != SEM_FAILED) { sem_close(p->semOwnedByFenix); p->semOwnedByFenix = SEM_FAILED; };
  if ((p->semOwnedByAstra) != SEM_FAILED) { sem_close(p->semOwnedByAstra); p->semOwnedByAstra = SEM_FAILED; };
  unlinkIpcFiles(p);
  freeNullifyAllIpcFilenames(p);
}
static
void unlinkIpcFiles(struct IPC *p) {
  char *s;
  s = p->nameShmF2A;
  if (s) {
    shm_unlink(s);
  }
  s = p->nameShmA2F;
  if (s) {
    shm_unlink(s);
  }
  s = p->nameSemOwnedByFenix;
  if (s) {
    sem_unlink(s);
  }
  s = p->nameSemOwnedByAstra;
  if (s) {
    sem_unlink(s);
  }
}
static
double *shmArrayBase(void *data) {
  return (double*)((char*)data + ((struct ShmHeader*)data)->offsetBytes);
}
static
size_t *shmWidthBase(void *data) {
  return (size_t*)((struct ShmHeader*)data+1);
}
static struct IPC *ipc = NULL;
static struct ShmHeader *f2a = MAP_FAILED;
static struct ShmHeader *a2f = MAP_FAILED;
static struct ShmHeader *shmLoad(const char *name) {
  size_t totalBytes;
  struct ShmHeader *shm;
  int fid;
  fid = shm_open(name, O_RDWR, 0640);
  if (fid == -1) {
    error_at_line(
      1, errno, __FILE__, __LINE__-3,
      "Fail to open shm '%s'", name);
  }
  shm = mmap(NULL, sizeof(struct ShmHeader), PROT_READ, MAP_SHARED, fid, 0);
  if (shm == MAP_FAILED) { close(fid); error(1, errno, "Fail to mmap for '%s'", name); };
  totalBytes = shm->totalBytes;
  munmap(shm, sizeof(struct ShmHeader));
  shm = mmap(NULL, totalBytes, PROT_WRITE|PROT_READ, MAP_SHARED, fid, 0);
  if (shm == MAP_FAILED) { close(fid); error(1, errno, "Fail to mmap for '%s'", name); };
  close(fid);
  return shm;
}
static void cleanupShmwr() {
  if (f2a != MAP_FAILED)
    munmap(f2a, f2a->totalBytes);
  if (a2f != MAP_FAILED)
    munmap(a2f, a2f->totalBytes);
  if (ipc) {
    destroyIPC(ipc);
    free(ipc);
  }
}
static void establishIPC() {
  int counter;
  if (ipc) {
    return;
  }
  atexit(cleanupShmwr);
  ipc = malloc(sizeof(struct IPC));
  initIPC(ipc);
  generateIPCFileNames(ipc, getpgid(0));
  ipc->semOwnedByAstra = sem_open(
        ipc->nameSemOwnedByAstra,
        O_CREAT | O_RDWR | O_EXCL, 0640,
        0);
  if (ipc->semOwnedByAstra == SEM_FAILED) {
    error_at_line(
      1, errno, __FILE__, __LINE__-3,
      "Fail to create semaphore '%s'", ipc->nameSemOwnedByAstra);
  }
  counter = 0;
  do {
    ipc->semOwnedByFenix =
      sem_open(ipc->nameSemOwnedByFenix, O_RDONLY);
    if (ipc->semOwnedByFenix == SEM_FAILED) {
      if (counter >= 5) {
        sem_close(ipc->semOwnedByAstra);
        sem_unlink(ipc->nameSemOwnedByAstra);
        error_at_line(
          1, errno, __FILE__, __LINE__-6,
          "Timeout for opening semaphore '%s'", ipc->nameSemOwnedByFenix);
      }
      sleep(1);
      counter++;
    }
  } while (ipc->semOwnedByFenix == SEM_FAILED);
  sem_wait(ipc->semOwnedByFenix);
  f2a = shmLoad(ipc->nameShmF2A);
  a2f = shmLoad(ipc->nameShmA2F);
  a2f->magic = 7690051;
  a2f->version = 1;
  sem_post(ipc->semOwnedByAstra);
}

void shmr_(double *first, ...) {
  va_list ap;
  size_t i;
  double *ptrShmVec;
  size_t *ptrWidth;
  double *arg;
  struct ShmHeader *shm;
  establishIPC();
  shm = f2a;
  sem_wait(ipc->semOwnedByFenix);
  ptrShmVec = shmArrayBase(shm);
  ptrWidth = shmWidthBase(shm);
  va_start(ap, first);
  for (i = 0; i < shm->nPort; ++i) {
    size_t width = *ptrWidth++;
    arg = (i == 0) ? first : (va_arg(ap, double*));
    memcpy(arg, ptrShmVec, width*sizeof(double));
    ptrShmVec += width;
  }
  va_end(ap);
}

void shmw_(double *first, ...) {
  va_list ap;
  size_t i;
  double *ptrShmVec;
  size_t *ptrWidth;
  double *arg;
  struct ShmHeader *shm;
  establishIPC();
  shm = a2f;
  ptrShmVec = shmArrayBase(shm);
  ptrWidth = shmWidthBase(shm);
  va_start(ap, first);
  for (i = 0; i < shm->nPort; ++i) {
    size_t width = *ptrWidth++;
    arg = (i == 0) ? first : (va_arg(ap, double*));
    memcpy(ptrShmVec, arg, width*sizeof(double));
    ptrShmVec += width;
  }
  va_end(ap);
  sem_post(ipc->semOwnedByAstra);
}
