#!/bin/bash -f

source /etc/profile.d/modules.sh

rootdir=`dirname $0`                # may be relative path
export AWD=`cd $rootdir/.. && pwd`  # ensure absolute path

platform=`$AWD/get_platform`
echo Installation for platform $platform

module purge

if [[ $platform == "gway" ]]
then
    module load cineca intel
elif [[ $platform == "iter" ]]
then
    module load SciPy-bundle/2020.11-intel-2020b
elif [[ $platform == "goblin" ]]
then
    module load anaconda/3
elif [[ $platform == "cz" ]]
then
    module load python3/anaconda3.5
    module load intelstudio/18
elif [[ $platform == "ga" ]]
then
    module load intel/2019
    module load conda/iris
elif [[ $platform == "ldaug" ]]
then
    module load enable-aug-dv-modules
    module load anaconda3
elif [[ $platform == "mit" ]]
then
    module load intel/2018-01
    module load anaconda3/2020.11
elif [[ $platform == "tok" ]]
then
    module load anaconda/3/2023.03
elif [[ $platform == "lx" ]]
then
    module load anaconda/3
fi

ulimit -s 50000
python ${AWD}/exe/as_exe.py "$@"
