#!/bin/bash

rootdir=`dirname $0`        # may be relative path
AWD=`cd $rootdir/.. && pwd` # ensure absolute path

platform=`$AWD/get_platform`
source $AWD/platform/env.$platform
if [[ ":$PATH:" != *":$PYTHON_BIN:"* ]]
then
    export PATH=${PYTHON_BIN}:${PATH}
fi

python3 ${AWD}/exe/as_exe.py "$@"
