#!/bin/bash

#JSON
JSON_HOME=${ASTRA_EXT}/json/9.0.2
export JSON_LIB=$JSON_HOME/lib/libjsonfortran.a
export JSON_INC=$JSON_HOME/inc

# SPIDER
SPIDER_HOME=${ASTRA_EXT}/spider/skip
#SPIDER_HOME=${ASTRA_EXT}/spider/apr26
if [ -f ${SPIDER_HOME}/lib/libspider.a ]; then
    export SPIDER_LIB=${SPIDER_HOME}/lib/libspider.a
else
    export SPIDER_LIB=""
fi

# TORBEAM

IRC_LIB="-L${COMP_LIBDIR} -lirc" # necessary for libtorbeam.so
TORB_HOME=${ASTRA_EXT}/torbeam/nov24
TORB_LIBDIR=${TORB_HOME}/lib
export TORB_LIB="-L${TORB_LIBDIR} -ltorbeamB  -Wl,-rpath,${TORB_LIBDIR} ${IRC_LIB}"

# RABBIT

RABBIT_HOME=${ASTRA_EXT}/rabbit/mar26
RABBIT_LIBDIR=${RABBIT_HOME}/lib
export RABBIT_LIB="-L${RABBIT_LIBDIR} -lrabbit -Wl,-rpath,${RABBIT_LIBDIR}"
export RABBIT_INC=${RABBIT_HOME}/inc

# TORIC-SSFPQL
TORFPQL_HOME=${ASTRA_EXT}/toric/apr26/intel/2025.1
export TORFPQL_LIBDIR=${TORFPQL_HOME}/lib/
export TORFPQL_INC=${TORFPQL_HOME}/include
export TORFPQL_LIB="-L${TORFPQL_LIBDIR} -ltoric -Wl,-rpath,${TORFPQL_LIBDIR} -L ${TORFPQL_LIBDIR} -lfmtout -lslatec -lodepack -Wl,-rpath,${TORFPQL_LIBDIR} -L/usr/lib64/ -lgmp  -L/mpcdf/soft/SLE_15/packages/znver4/fftw/intel_2025.1-2025.1.0/3.3.9/lib/ -lfftw3  -Wl,-rpath,/mpcdf/soft/SLE_15/packages/znver4/fftw/intel_2025.1-2025.1.0/3.3.9/lib/"

# QuaLiKiZ

QLK_HOME=${ASTRA_EXT}/qualikiz/nov24
export QLK_INC=${QLK_HOME}/inc
export QLK_LIB=${QLK_HOME}/lib/libQLK-intel-release-default.a

QLKNN_HOME=${ASTRA_EXT}/qlk_nn/nov24
export QLKNN_INC=${QLKNN_HOME}/inc
export QLKNN_LIB=${QLKNN_HOME}/lib/libQLKNN-intel-release-default.a

# TGLF

TGLF_HOME=${ASTRA_EXT}/tglf/jun25
export TGLF_INC=${TGLF_HOME}/inc
export TGLF_LIB=${TGLF_HOME}/lib/libtglf.a

# NEO

NEO_HOME=${ASTRA_EXT}/neo/dec24
NEO_LIBDIR=${NEO_HOME}/lib
export NEO_INC=${NEO_HOME}/inc
export NEO_LIB="${NEO_LIBDIR}/neo_lib.a ${NEO_LIBDIR}/nclass_lib.a ${NEO_LIBDIR}/UMFPACK_lib.a ${NEO_LIBDIR}/math_lib.a ${NEO_LIBDIR}/expro_lib.a ${NEO_LIBDIR}/geo_lib.a"
