#!/bin/bash

platform=`$AWD/get_platform`

#JSON

JSON_HOME=${ASTRA_EXT}/json/9.0.2
TORBEAM_HOME=${ASTRA_EXT}/torbeam/nov24
RABBIT_HOME=${ASTRA_EXT}/rabbit/may26
TGLF_HOME=${ASTRA_EXT}/tglf/jun25
NEO_HOME=${ASTRA_EXT}/neo/dec24
QLK_HOME=${ASTRA_EXT}/qualikiz/nov24
QLKNN_HOME=${ASTRA_EXT}/qlk_nn/nov24
if [[ "$platform" = "darwin" ]]; then
    JSON_HOME=${ASTRA_EXT}/json
    TORBEAM_HOME=${ASTRA_EXT}/torbeam
    RABBIT_HOME=${ASTRA_EXT}/rabbit
    TGLF_HOME=${ASTRA_EXT}/tglf
    NEO_HOME=${ASTRA_EXT}/neo
    QLK_HOME=${ASTRA_EXT}/qualikiz
    QLKNN_HOME=${ASTRA_EXT}/qlk_nn
fi
export JSON_LIB=$JSON_HOME/lib/libjsonfortran.a
export JSON_INC=$JSON_HOME/inc
#export STELLOPT_HOME=/tokp/work/software/TOK_2023/software/stellopt/6.00/STELLOPT/
export STELLOPT_HOME=${ASTRA_EXT}/STELLOPT/

# SPIDER

SPIDER_HOME=${ASTRA_EXT}/spider/jun26
SPIDER_LIBDIR=${SPIDER_HOME}/lib
export SPIDER_LIB=${SPIDER_LIBDIR}/libspider.a
if [ -f ${SPIDER_LIB} ]; then
    export SPIDER_INC=-I${SPIDER_HOME}/inc
else
    unset SPIDER_LIB
fi

# TORBEAM

IRC_LIB="-L${COMP_LIBDIR} -lirc" # necessary for libtorbeam.so
TORBEAM_LIBDIR=${TORBEAM_HOME}/lib
if [ -f ${TORBEAM_LIBDIR}/libtorbeamB.so ]; then
    export TORBEAM_LIB="-L${TORBEAM_LIBDIR} -ltorbeamB -Wl,-rpath,${TORBEAM_LIBDIR} ${IRC_LIB}"
else
    unset TORBEAM_LIB
fi

# RABBIT

RABBIT_LIBDIR=${RABBIT_HOME}/lib
if [ -f ${RABBIT_LIBDIR}/librabbit.so ] || \
   [ -f ${RABBIT_LIBDIR}/librabbit.dylib ]; then
    export RABBIT_LIB="-L${RABBIT_LIBDIR} -lrabbit -Wl,-rpath,${RABBIT_LIBDIR}"
else
    unset RABBIT_LIB
fi
export RABBIT_INC=${RABBIT_HOME}/inc

# TORIC-SSFPQL

TORIC_HOME="${ASTRA_EXT}/toric/apr26/intel/2025.1"
TORIC_LIBDIR=${TORIC_HOME}/lib
export TORIC_INC=${TORIC_HOME}/include
FFTW_LIBDIR=/mpcdf/soft/SLE_15/packages/znver4/fftw/intel_2025.1-2025.1.0/3.3.9/lib
if [ -f ${TORIC_LIBDIR}/libtoric.so ]; then
    export TORIC_LIB="-L${TORIC_LIBDIR} -ltoric -lslatec -lodepack -Wl,-rpath,${TORIC_LIBDIR} -L${FFTW_LIBDIR} -lfftw3 -Wl,-rpath,${FFTW_LIBDIR} -lgmp"
else
    unset TORIC_LIB
fi

# QuaLiKiZ

QLK_LIBDIR=${QLK_HOME}/lib
export QLK_INC=${QLK_HOME}/inc
export QLK_LIB=${QLK_LIBDIR}/libQLK-intel-release-default.a
if [ -f ${QLK_LIBDIR}/libQLK-gcc-release-default.a ]; then
    export QLK_LIB=${QLK_LIBDIR}/libQLK-gcc-release-default.a
fi

# Qualikiz Neural-Network

QLKNN_LIBDIR=${QLKNN_HOME}/lib
export QLKNN_INC=${QLKNN_HOME}/inc
export QLKNN_LIB=${QLKNN_LIBDIR}/libQLKNN-intel-release-default.a
if [ -f ${QLKNN_LIBDIR}/libQLKNN-gcc-release-default.a ]; then
    export QLKNN_LIB=${QLKNN_LIBDIR}/libQLKNN-gcc-release-default.a
fi
if [ ! -f ${QLKNN_LIB} ]; then
    unset QLKNN_LIB
fi

# TGLF

export TGLF_INC=${TGLF_HOME}/inc
export TGLF_LIB=${TGLF_HOME}/lib/libtglf.a
if [ ! -f ${TGLF_LIB} ]; then
    unset TGLF_LIB
fi

# NEO

NEO_LIBDIR=${NEO_HOME}/lib
export NEO_INC=${NEO_HOME}/inc
export NEO_LIB="${NEO_LIBDIR}/neo_lib.a ${NEO_LIBDIR}/nclass_lib.a ${NEO_LIBDIR}/UMFPACK_lib.a ${NEO_LIBDIR}/math_lib.a ${NEO_LIBDIR}/expro_lib.a ${NEO_LIBDIR}/geo_lib.a"
