#!/bin/bash

#JSON
JSON_HOME=${ASTRA_EXT}/json/gcc_9.0.2
export JSON_LIB=$JSON_HOME/lib/libjsonfortran.a
export JSON_INC=$JSON_HOME/inc

# SPIDER
SPIDER_HOME=${ASTRA_EXT}/spider/gcc_apr26
if [ -f ${SPIDER_HOME}/lib/libspider.a ]; then
    export SPIDER_LIB=${SPIDER_HOME}/lib/libspider.a
else
    export SPIDER_LIB=""
fi

# TORBEAM

IRC_LIB="-L${COMP_LIBDIR} -lirc" # necessary for libtorbeam.so
TORB_HOME=${ASTRA_EXT}/torbeam/gcc_apr26
TORB_LIBDIR=${TORB_HOME}/lib
export TORB_LIB="-L${TORB_LIBDIR} -ltorbeamB  -Wl,-rpath,${TORB_LIBDIR} ${IRC_LIB}"

# RABBIT

RABBIT_HOME=${ASTRA_EXT}/rabbit/gcc_may26
RABBIT_LIBDIR=${RABBIT_HOME}/lib
export RABBIT_LIB="-L${RABBIT_LIBDIR} -lrabbit -Wl,-rpath,${RABBIT_LIBDIR}"
export RABBIT_INC=${RABBIT_HOME}/inc

# QuaLiKiZ

QLK_HOME=${ASTRA_EXT}/qualikiz/gcc_apr26
export QLK_INC=${QLK_HOME}/inc
export QLK_LIB=${QLK_HOME}/lib/libQLK-gcc-release-default.a

QLKNN_HOME=${ASTRA_EXT}/qlk_nn/gcc_apr26
export QLKNN_INC=${QLKNN_HOME}/inc
export QLKNN_LIB=${QLKNN_HOME}/lib/libQLKNN-gcc-release-default.a

# TGLF

TGLF_HOME=${ASTRA_EXT}/tglf/gcc_apr26
export TGLF_INC=${TGLF_HOME}/inc
export TGLF_LIB=${TGLF_HOME}/lib/libtglf.a

# NEO

NEO_HOME=${ASTRA_EXT}/neo/gcc_apr26
NEO_LIBDIR=${NEO_HOME}/lib
export NEO_INC=${NEO_HOME}/inc
export NEO_LIB="${NEO_LIBDIR}/neo_lib.a ${NEO_LIBDIR}/nclass_lib.a ${NEO_LIBDIR}/UMFPACK_lib.a ${NEO_LIBDIR}/math_lib.a ${NEO_LIBDIR}/expro_lib.a ${NEO_LIBDIR}/geo_lib.a"
