#!/bin/bash

equ_file=$1
exp_file=$2
TASK=$3
if [[ $# > 3 ]]; then
    WAIT_SLURM=$4
else
    WAIT_SLURM=""
fi

rootdir=`dirname $0`                  # may be relative path
export AWD=`cd $rootdir/.. && pwd`    # ensure absolute path

cd $AWD

# Get platform-dependent compiler paths
platform=`$AWD/get_platform`
source $AWD/platform/env.$platform

source $AWD/exe/astra_rc

export CHECKALLCOMP=" "
#export CHECKALLCOMP="-check all -traceback"

ulimit -s 100000

THREADS_PER_CORE=$(lscpu | awk -F: '/Thread\(s\) per core/ {gsub(/ /,"",$2); print $2}')
NPROC=`nproc`
if (( NPROC < THREADS_PER_CORE ));
then
    export MAX_NWORKERS=1
else
    export MAX_NWORKERS=$(( NPROC / THREADS_PER_CORE ))
fi
echo 'Max nworkers' $MAX_NWORKERS

echo Compile main ASTRA executable $equ_file $AWD 
make -f exe/Makefile MODEL=$equ_file WORKFLOW=$AWD/src/for/stepup.f90
status=$?
if [ $status -ne 0 ]
then
    echo Error from exe/Makefile-compilation, exiting
    exit 1
fi

echo Compile IPC programs
make -f exe/Makexpr
status=$?
if [ $status -ne 0 ]
then
    echo Error from exe/Makexpr-compilation, exiting
    exit 2
fi

exe/CheckObjs
status=$?
if [ $status -ne 0 ]
then
    echo CheckObjs failed: conflicting object names
    exit 3
fi

# Execution

ATASK=$AWD/bin/$equ_file.exe

#if [ "$TASK" = 'BGDs' ] # for testing only
if [ "$TASK" = 'BGD' ]
then
    if ! command -v sbatch &> /dev/null
    then
        echo Running $ATASK without graphic interactive window
        $ATASK
    else
        bat="$AWD/exe/batch.sh"
        cat << EOT > $bat
#!/bin/sh
#SBATCH -J astra_${USER}
#SBATCH --partition=${SL_QUEUE}
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=128
#SBATCH --mem-per-cpu 1GB
#SBATCH --time=12:00:00
#SBATCH --mail-type=none
export OMP_NUM_THREADS=\${SLURM_CPUS_PER_TASK:-1}
export OMP_PLACES=cores
export OMP_PROC_BIND=close
export ASTRA_EXT=${ASTRA_EXT}
export PATH=${PATH}
export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}
$ATASK
EOT

        echo sbatch $bat
        date
	pwd
#        sbatch -W $bat # -W: waiting for process to finish before running json2cdf 
        sbatch $WAIT_SLURM $bat
    fi
else
    echo Running $ATASK
    $ATASK
    echo ASTRA normal exit
fi
