#!/bin/bash

equ_file=$1
exp_file=$2
TASK=$3
if [[ $# > 3 ]]; then
    WAIT_SLURM=$4
else
    WAIT_SLURM=""
fi

rootdir=`dirname $0`                  # may be relative path
export AWD=`cd $rootdir/.. && pwd`    # ensure absolute path

cd $AWD

platform=`$AWD/get_platform`

source $AWD/platform/env.$platform
source $AWD/exe/astra_rc

export CHECKALLCOMP=" "
#export CHECKALLCOMP="-check all -traceback"

ulimit -s 100000

echo Compile main ASTRA executable $equ_file $AWD 
make -f exe/Makefile MODEL=$equ_file WORKFLOW=$AWD/src/for/stepup.f90
status=$?
if [ $status -ne 0 ]
then
    echo Error from exe/Makefile-compilation, exiting
    exit 1
fi

echo Compile IPC programs
make -f exe/Makexpr
make -f exe/Makechunk
status=$?
if [ $status -ne 0 ]
then
    echo Error from exe/Makexpr-compilation, exiting
    exit 2
fi

exe/CheckObjs
status=$?
if [ $status -ne 0 ]
then
    echo CheckObjs failed: conflicting object names
    exit 3
fi

# Execution

ATASK=$AWD/bin/$equ_file.exe

#if [ "$TASK" = 'BGDs' ] # for testing only
if [ "$TASK" = 'BGD' ]
then
    if ! command -v sbatch &> /dev/null
    then
        echo Running $ATASK without graphic interactive window
        $ATASK
    else
        bat="$AWD/exe/batch.sh"
        cat << EOT > $bat
#!/bin/sh
#SBATCH -J astra_${USER}
#SBATCH --partition=p.tok
#SBATCH --qos=p.tok.48h
#SBATCH --nodes=6
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=16
#SBATCH --mem-per-cpu 1GB
#SBATCH --time=12:00:00
#SBATCH --mail-type=none
export OMP_NUM_THREADS=\${SLURM_CPUS_PER_TASK:-1}
export OMP_PLACES=cores
export I_MPI_ROOT=${I_MPI_ROOT}
export I_MPI_FABRICS=shm:ofi
export I_MPI_SPAWN=on
#export PMI_DEBUG=1
#export I_MPI_DEBUG=5
export FI_PROVIDER_PATH=${I_MPI_ROOT}/libfabric/lib/prov
export ASTRA_EXT=${ASTRA_EXT}
export PATH=${PATH}
export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:${I_MPI_ROOT}/libfabric/lib
$ATASK
EOT

        echo sbatch $bat
        date
	pwd
#        sbatch -W $bat # -W: waiting for process to finish before running json2cdf 
        sbatch $WAIT_SLURM $bat
    fi
else
    echo Running $ATASK
    $ATASK
    echo ASTRA normal exit
    echo
    for mod_name in tglfi qlkzi qlki neo
    do
        PID=$(ps aux | grep $mod_name | grep 'R+' | grep $USER | awk '{print $2}')
        if [ ! -z "$PID" ];
        then
            for p_id in $PID
            do
                kill -9 $p_id
            done
        fi
    done
fi
