#!/bin/bash

LIBDIR=$AWD/lib

ERR=0
echo ""

LIB1=$LIBDIR/libsbr.a
OBJ1=`ar -tv $LIB1 | awk '{print $NF}'`
LIB2=$LIBDIR/libfnc.a
OBJ2=`ar -tv $LIB2 | awk '{print $NF}'`
for OB1 in $OBJ1
do
    for OB2 in $OBJ2
    do
        if [ $OB1 == $OB2 ]
        then
            echo Conflicting $OB1: in $LIB1 and $LIB2
            echo No ASTRA simulation started
            echo ""
            ERR=1
        fi
    done
done

exit $ERR
